import {
  Building2,
  FileText,
  Target,
  Lightbulb,
  MessageSquare,
  Mail,
  BarChart3,
  Sparkles,
} from "lucide-react";

export function ProductPreviewSection() {
  return (
    <section className="bg-surface py-20 md:py-28">
      <div className="mx-auto max-w-7xl px-6 lg:px-8">
        <div className="mx-auto max-w-2xl text-center">
          <p className="text-sm font-semibold uppercase tracking-widest text-primary">
            Product preview
          </p>
          <h2 className="mt-3 font-display text-3xl font-extrabold tracking-tight text-foreground sm:text-4xl">
            See what a generated brief looks like
          </h2>
          <p className="mt-4 text-lg text-muted-foreground">
            Here&apos;s a sample brief for a fictional company — this is what
            you get after one click.
          </p>
        </div>

        <div className="relative mx-auto mt-14 max-w-4xl">
          <div className="rounded-3xl border border-border/60 bg-card shadow-2xl shadow-primary/5 overflow-hidden">
            {/* Header */}
            <div className="border-b border-border/50 bg-gradient-to-r from-primary/5 to-accent/5 px-8 py-5">
              <div className="flex items-center gap-4">
                <div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10">
                  <Building2 className="h-6 w-6 text-primary" />
                </div>
                <div>
                  <h3 className="font-display text-lg font-bold text-foreground">
                    Acme Corp — Discovery Brief
                  </h3>
                  <p className="text-sm text-muted-foreground">
                    Generated by Lead Brief Generator · B2B SaaS · Series A
                  </p>
                </div>
                <div className="ml-auto hidden items-center gap-1.5 rounded-full bg-accent/15 px-3 py-1 text-xs font-semibold text-accent sm:flex">
                  <Sparkles className="h-3 w-3" />
                  AI Generated
                </div>
              </div>
            </div>

            {/* Content */}
            <div className="grid gap-5 p-6 md:grid-cols-2 md:p-8">
              <PreviewCard
                icon={<FileText className="h-4 w-4" />}
                title="Company Summary"
              >
                Acme Corp is a cloud-based project management platform serving
                mid-market B2B teams. Founded in 2021, they recently closed a
                Series A and are scaling from 45 to 80 employees. Their core
                product helps teams manage cross-functional workflows.
              </PreviewCard>
              <PreviewCard
                icon={<BarChart3 className="h-4 w-4" />}
                title="Sales Situation"
              >
                Actively hiring across sales and engineering. Recent fundraise
                suggests expansion phase. Likely evaluating new tools to support
                scale. Published case studies indicate focus on enterprise
                readiness.
              </PreviewCard>
              <PreviewCard
                icon={<Target className="h-4 w-4" />}
                title="Likely Pain Points"
              >
                <ul className="mt-1 space-y-1 text-muted-foreground">
                  <li>• Manual reporting across multiple tools</li>
                  <li>• Limited executive-level dashboards</li>
                  <li>• Onboarding bottleneck for new team members</li>
                  <li>• Cross-team dependency tracking gaps</li>
                </ul>
              </PreviewCard>
              <PreviewCard
                icon={<Lightbulb className="h-4 w-4" />}
                title="Opportunity Areas"
              >
                <ul className="mt-1 space-y-1 text-muted-foreground">
                  <li>• Unified analytics and reporting layer</li>
                  <li>• Automated project status updates</li>
                  <li>• Integration with existing CRM stack</li>
                  <li>• Enterprise-grade permission controls</li>
                </ul>
              </PreviewCard>
              <PreviewCard
                icon={<MessageSquare className="h-4 w-4" />}
                title="Discovery Questions"
              >
                <ul className="mt-1 space-y-1 text-muted-foreground">
                  <li>• How are you tracking cross-team dependencies today?</li>
                  <li>
                    • What does your executive reporting workflow look like?
                  </li>
                  <li>
                    • What is the biggest bottleneck when onboarding new PMs?
                  </li>
                </ul>
              </PreviewCard>
              <PreviewCard
                icon={<Mail className="h-4 w-4" />}
                title="Follow-Up Email"
              >
                <p className="mt-1 text-muted-foreground italic">
                  &quot;Hi Sarah, thanks for the call today. Based on our
                  conversation about scaling project visibility across teams, I
                  wanted to share a few ideas on how we have helped similar B2B
                  SaaS companies streamline reporting&quot;
                </p>
              </PreviewCard>
            </div>
          </div>
          {/* Decorative glow */}
          <div className="pointer-events-none absolute -inset-6 -z-10 rounded-[2rem] bg-gradient-to-r from-primary/8 via-accent/5 to-primary/8 blur-3xl" />
        </div>
      </div>
    </section>
  );
}

function PreviewCard({
  icon,
  title,
  children,
}: {
  icon: React.ReactNode;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="rounded-xl border border-border/40 bg-surface/50 p-4">
      <div className="mb-2 flex items-center gap-2 text-sm font-bold text-primary">
        {icon}
        {title}
      </div>
      <div className="text-sm leading-relaxed">{children}</div>
    </div>
  );
}
